apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: github-actions-workshop
  namespace: user-15-devspaces
  annotations:
    che.eclipse.org/che-editor: che-incubator/che-code/latest
spec:
  routingClass: che
  started: true
  contributions:
    - name: ide
      uri: http://devspaces-dashboard.openshift-devspaces.svc.cluster.local:8080/dashboard/api/editors/devfile?che-editor=che-incubator/che-code/latest
  template:
    components:
      - name: universal-developer-image
        container:
          image: registry.redhat.io/devspaces/udi-rhel9@sha256:2708a8082c9c0aa569e31c79695483311cae3533e42b950fd02384b0def75415
          sourceMapping: /projects
          env:
            - name: HOST_USERS
              value: "true"
    projects:
    - git:
        checkoutFrom:
          revision: main
        remotes:
          origin: https://github.com/syamaguc-demo/github-actions-ops-workshop-user-15.git
      name: github-actions-ops-workshop
